Website/src/Website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from Blog import views
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index),
    url(r'^signup/$', views.signup),
    url(r'^login/$',views.login),
    url(r'^logout/$',views.logout),
    url(r'^setpasswd/$',views.setpasswd),
    url(r'^addbook/$',views.addbook),
    url(r'^viewbook/$',views.viewbook),
    url(r'^viewbook/detail/$',views.detail),
    url(r'^image/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PATH}),
]

Website/src/Blog/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.
class MyUser(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length = 16)
    permission = models.IntegerField()

    def __str__(self):
        return self.user.username

class Book(models.Model):
    name = models.CharField(max_length = 128)
    price = models.FloatField()
    author = models.CharField(max_length = 128)
    pubDate = models.DateField()
    typ = models.CharField(max_length = 128)

    class META:
        ordering = ['name']

    def __str__(self):
        return self.name

class Img(models.Model):
    name = models.CharField(max_length = 128)
    desc = models.TextField()
    img = models.ImageField(upload_to = 'image')
    book = models.ForeignKey(Book)

    class META:
        ordering = ['name']

    def __str__(self):
        return self.name
# Create your models here.

Website/src/Blog/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import loader,Context,RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.contrib.auth.models import User
from django.contrib import auth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from Blog.models import *


def get_type_list():
    book_list = Book.objects.all()
    type_list = set()
    for book in book_list:
        type_list.add(book.typ)
    return list(type_list)


def index(req):
    username = req.session.get('username', '')
    if username:
        user = MyUser.objects.get(user__username=username)
    else:
        user = ''
    content = {'active_menu': 'homepage', 'user': user}
    return render_to_response('index.html', content)


def signup(req):
    if req.session.get('username', ''):
        return HttpResponseRedirect('/')
    status = ''
    if req.POST:
        post = req.POST
        passwd = post.get('passwd', '')
        repasswd = post.get('repasswd', '')
        if passwd != repasswd:
            status = 're_err'
        else:
            username = post.get('username', '')
            if User.objects.filter(username=username):
                status = 'user_exist'
            else:
                newuser = User.objects.create_user(username=username, password=passwd, email=post.get('email', ''))
                newuser.save()
                new_myuser = MyUser(user=newuser, nickname=post.get('nickname'), permission=1)
                new_myuser.save()
                status = 'success'
    content = {'active_menu': 'homepage', 'status': status, 'user': ''}
    return render_to_response('signup.html', content, context_instance=RequestContext(req))


def login(req):
   # if req.session.get('username', ''):
   #     return HttpResponseRedirect('/')
    print("success")
    status = ''
    if req.POST:
        post = req.POST
        username = post.get('username', '')
        password = post.get('passwd', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(req, user)
                req.session['username'] = username
                return HttpResponseRedirect('/')
            else:
                status = 'not_active'
        else:
            status = 'not_exist_or_passwd_err'
    content = {'active_menu': 'homepage', 'status': status, 'user': ''}
    return render_to_response('login.html', content, context_instance=RequestContext(req))


def logout(req):
    auth.logout(req)
    return HttpResponseRedirect('/')


def setpasswd(req):
    username = req.session.get('username', '')
    if username != '':
        user = MyUser.objects.get(user__username=username)
    else:
        return HttpResponseRedirect('/login/')
    status = ''
    if req.POST:
        post = req.POST
        if user.user.check_password(post.get('old', '')):
            if post.get('new', '') == post.get('new_re', ''):
                user.user.set_password(post.get('new', ''))
                user.user.save()
                status = 'success'
            else:
                status = 're_err'
        else:
            status = 'passwd_err'
    content = {'user': user, 'active_menu': 'homepage', 'status': status}
    return render_to_response('setpasswd.html', content, context_instance=RequestContext(req))


def addbook(req):
    username = req.session.get('username', '')
    if username != '':
        user = MyUser.objects.get(user__username=username)
    else:
        return HttpResponseRedirect('/login/')
    if user.permission < 2:
        return HttpResponseRedirect('/')
    status = ''
    if req.POST:
        post = req.POST
        newbook = Book(
            name=post.get('name',''), \
            author=post.get('author',''), \
            typ=post.get('typ',''), \
            price=post.get('price', ''), \
            pubDate=post.get('pubdate', ''), \
            )
        newbook.save()
        status = 'success'
    content = {'user': user, 'active_menu': 'addbook', 'status': status}
    return render_to_response('addbook.html', content, context_instance=RequestContext(req))


def viewbook(req):
    username = req.session.get('username', '')
    if username != '':
        user = MyUser.objects.get(user__username=username)
    else:
        user = ''
    type_list = get_type_list()
    book_type = req.GET.get('typ', 'all')
    if book_type == '':
        book_lst = Book.objects.all()
    elif book_type not in type_list:
        book_type = 'all'
        book_lst = Book.objects.all()
    else:
        book_lst = Book.objects.filter(typ=book_type)

    if req.POST:
        post = req.POST
        keywords = post.get('keywords','')
        book_lst = Book.objects.filter(name__contains=keywords)
        book_type = 'all'

    paginator = Paginator(book_lst, 5)
    page = req.GET.get('page')
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(paginator.num_pages)

    content = {'user': user, 'active_menu': 'viewbook', 'type_list': type_list, 'book_type': book_type, 'book_list': book_list}
    return render_to_response('viewbook.html', content, context_instance=RequestContext(req))


def detail(req):
    username = req.session.get('username','')
    if username != '':
        user = MyUser.objects.get(user__username=username)
    else:
        user = ''
    Id = req.GET.get('id','')
    if Id == '':
        return HttpResponseRedirect('/viewbook/')
    try:
        book = Book.objects.get(pk=Id)
    except:
        return HttpResponseRedirect('/viewbook/')
    img_list = Img.objects.filter(book=book)
    content = {'user': user, 'active_menu': 'viewbook', 'book': book, 'img_list':img_list}
    return render_to_response('detail.html', content)

Website/src/Blog/templates/addbook.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">添加成功</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">添加图书</h1>

				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">书名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_name" required name="name" autofocus>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_author" class="col-md-3 control-label">作者：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="author" id="id_author">
					</div>
				</div>

				<div class="form-group">
					<label for="id_typ" class="col-md-3 control-label">类型：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="typ" id="id_typ">
					</div>
				</div>

				<div class="form-group">
					<label for="id_price" class="col-md-3 control-label">价格：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="price" id="id_price">
					</div>
				</div>

				<div class="form-group">
					<label for="id_pubdate" class="col-md-3 control-label">出版日期：</label>
					<div class="col-md-9">
						<input type="date" class="form-control" required name="pubdate" id="id_pubdate">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock %}

Website/src/Blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-theme.min.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
		<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
		<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
		<!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!--Here is the navbar-->
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-basepage">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="/" class="navbar-brand">Library</a>
				</div>

				<div class="collapse navbar-collapse" id="navbar-collapse-basepage">
					<ul class="nav navbar-nav">
						<li id="homepage"><a href="/">主页</a></li>
						{% if user.permission > 1 %}
							<li id="addbook"><a href="/addbook/">添加图书</a></li>
						{% endif %}
						<li id="viewbook"><a href="/viewbook/">查看图书</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if user %}
							<li><p class="navbar-text">欢迎你&nbsp;&nbsp;<span id="base_name">{{ user.nickname }}</span></p></li>
							<li><a href="/logout/">注销</a></li>
							<li><a href="/setpasswd/">修改密码</a></li>
						{% else %}
							<li><a href="/signup/">注册</a></li>
							<li><a href="/login/">登录</a></li>
						{% endif %}
					</ul>
				</div>

			</div>
		</nav>
		<!-- /nav -->
		<!-- header -->
		<header class="jumbotron subhead" id="header-base">
			<div class="container">
				<h1>图书管理系统</h1>
				<h3>&emsp;&emsp;知识改变命运</h3>
			</div>
		</header>
		<!-- /.header -->
		<!-- main part -->
		{% block content %}{% endblock %}
		<!-- /.main -->
	
		<!-- footer -->	
		<footer class="footer" role="contentinfo">
			<hr>
			<div class="container">
				<p class="text-center"><strong>HITCS</strong></p>
				<p class="text-center">©All rights reserved</p>
				<h5 class="text-center"> Powered by&nbsp;<a href="http://taobupt.github.io/">Wang Tao</a></h5>
			</div>
		</footer>
		<!-- /.footer-->
		<script type="text/javascript">
		    var act = document.getElementById("{{ active_menu }}");
		    act.setAttribute("class","active");
		</script>
	</body>
</html>

Website/src/Blog/templates/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="col-md-5">
				{% if img_list %}
					<div id="carousel-generic" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
						{% for item in img_list %}
							<li data-target="#carousel-generic" data-slide-to="{{forloop.counter0}}" {% if forloop.first %}class="active"{% endif %}></li>
						{% endfor %}
						</ol>
						<div class="carousel-inner" role="listbox">
						{% for img in img_list %}
							<div {% if forloop.first %}class="item active"{%else%}class="item"{% endif %}>
								<img class="img-rounded" src="/{{img.img}}">
							</div>
						{% endfor %}
						</div>
						<a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left"></span>
						</a>
						<a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right"></span>
						</a>
					</div>
				{% else %}
					<p class="text-center">暂无图片</p>
				{% endif %}
			</div>
			<div class="col-md-6 col-md-offset-1">
				<h2 class="text-center">{{book.name}}</h2>
				<br>
				<h3>作者：{{book.author}}</h3>
				<h3>类别：{{book.typ}}</h3>
				<h3>出版日期：{{book.pubDate|date:"Y-m-d"}}</h3>
				<h3>价格：{{ book.price|floatformat:2 }}</h3>
			</div>
		</div>
	</div>
</div>

{% endblock %}

Website/src/Blog/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}图书管理{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 well">
			<h2>&emsp;&emsp;Here is the homepage!</h2>
			<h3 class="text-center">Email:<span  class="text-info">wangtao665@bupt.edu.cn</span></h3>
		</div>
	</div>
</div>

{% endblock %}

Website/src/Blog/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
<html lang="zh-cn">
<meta charset="utf-8">
{% block title %}登陆{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'not_active' %}
				<div class="well">
					<h2 class="text-danger text-center">用户已被封禁</h2>
				</div>
			{% elif status == 'not_exist_or_passwd_err' %}
				<div class="well">
					<h2 class="text-danger text-center">用户不存在或密码错误</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">请登陆</h1>

				<div class="form-group">
					<label for="id_user_name" class="col-md-3 control-label">用户名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_passwd" class="col-md-3 control-label">密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="passwd" id="id_passwd">
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">登陆</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}
</html>

Website/src/Blog/templates/setpasswd.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}修改密码{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'passwd_err' %}
				<div class="well">
					<h2 class="text-danger text-center">密码错误</h2>
				</div>
			{% elif status == 're_err' %}
				<div class="well">
					<h2 class="text-warning text-center">密码重复错误</h2>
				</div>
			{% elif status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">修改成功</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">修改密码</h1>
				<div class="form-group">
					<label for="id_old" class="col-md-3 control-label">原始密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="old" id="id_old">
					</div>
				</div>
				<div class="form-group">
					<label for="id_new" class="col-md-3 control-label">新密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="new" id="id_new">
					</div>
				</div>
				<div class="form-group">
					<label for="id_new_re" class="col-md-3 control-label">重复密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="new_re" id="id_new_re">
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit">提交</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

Website/src/Blog/templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}注册{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
			{% if status == 'success' %}
				<div class="well">
					<h2 class="text-success text-center">注册成功！</h2>
				</div>
			{% elif status == 're_err' %}
				<div class="well">
					<h2 class="text-warning text-center">密码重复错误</h2>
				</div>
			{% elif status == 'user_exist' %}
				<div class="well">
					<h2 class="text-danger text-center">用户已经存在</h2>
				</div>
			{% endif %}
			<form method="POST" role="form" class="form-horizontal">
				{% csrf_token %}
				<h1 class="form-signin-heading text-center">请注册</h1>

				<div class="form-group">
					<label for="id_user_name" class="col-md-3 control-label">用户名：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" id="id_user_name" required name="username" autofocus>
						<span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
					</div>	
				</div>

				<div class="form-group">
					<label for="id_name" class="col-md-3 control-label">昵称：</label>
					<div class="col-md-9">
						<input type="text" class="form-control" required name="nickname" id="id_name">
					</div>
				</div>

				<div class="form-group">
					<label for="id_passwd" class="col-md-3 control-label">密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="passwd" id="id_passwd">
					</div>
				</div>

				<div class="form-group">
					<label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
					<div class="col-md-9">
						<input type="password" class="form-control" required name="repasswd" id="id_repasswd">
					</div>	
				</div>
				
				<div class="form-group">
					<label for="id_email" class="col-md-3 control-label">电子邮件：</label>
					<div class="col-md-9">
						<input type="email" class="form-control" required name="email" id="id_email">
					</div>	
				</div>

				<div class="form-group">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>

{% endblock %}

Website/src/Blog/templates/viewbook.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}查看图书{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="col-md-2">
				<div class="list-group">
					<a href="/viewbook/" class="list-group-item" id="id_typ_all">
						全部图书
					</a>
					{% for typ in type_list %}
					<a href="/viewbook?typ={{typ}}" class="list-group-item" id="id_typ_{{typ}}">
						{{ typ }}
					</a>
					{% endfor %}
				</div>
				<script type="text/javascript">
				    var act_typ = document.getElementById("id_typ_{{book_type}}");
				    var new_class = act_typ.getAttribute("class") + " active"
				    act_typ.setAttribute("class",new_class);
				</script>
			</div>
			<div class="col-md-9 col-md-offset-1">
				<div class="col-md-4 col-md-offset-8">
					<form role="form" method="post" name="search_form">
						{% csrf_token %}
						<input type="search" class="form-control" name="keywords" placeholder="Enter keywords to search" id="id_search_input" onkeyup="whenkeyup()" autofocus="True">
					</form>
				</div>
				<script type="text/javascript">
					function whenkeyup () {
						var oldvalue = document.getElementById('id_search_input').value
						setTimeout(function(){
							var newvalue = document.getElementById('id_search_input').value
							if (oldvalue == newvalue) {
								document.search_form.submit();
							};
						},1500);
					}
				</script>
				<table class="table table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>书名</th>
							<th>作者</th>
							<th>出版日期</th>
							<th>定价</th>
						</tr>
					</thead>
					<tbody>
						{% for book in book_list %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td><a href="/viewbook/detail/?id={{book.id}}">{{ book.name }}</a></td>
							<td>{{ book.author }}</td>
							<td>{{ book.pubDate|date:"Y-m-d" }}</td>
							<td>{{ book.price|floatformat:2 }}</td>
						</tr>
						{% empty %}
						<tr>
							<td>暂无图书</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<nav>
					<ul class="pager">
						{% if book_list.has_previous %}
							<li class="previous"><a href="?typ={{book_type}}&page={{ book_list.previous_page_number }}">上一页</a></li>
						{% else %}
							<li class="previous disabled"><a href="#">上一页</a></li>
						{% endif %}
						第 {{ book_list.number }} / {{ book_list.paginator.num_pages }}页
						{% if book_list.has_next %}
							<li class="next"><a href="?typ={{book_type}}&page={{ book_list.next_page_number }}">下一页</a></li>
						{% else %}
							<li class="next disabled"><a href="#">下一页</a></li>
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>


{% endblock %}